---

- hosts: all
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes

  - name: install web-base packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
